In [20]:
# Import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [21]:
# Read in data
data = pd.read_csv('data.csv')
print(data.columns)
data.head()

Index(['id', 'day_in_study', 'sedentary_mins', 'active_mins', 'glucose_mean',
       'rhr_mean', 'minutes_asleep', 'minutes_awake', 'sleep_efficiency_mean',
       'sleep_score_overall', 'sleep_score_revitalization',
       'sleep_score_duration', 'study_interval', 'is_weekend', 'phase', 'lh',
       'estrogen', 'pdg', 'flow_volume', 'flow_color', 'appetite',
       'exerciselevel', 'headaches', 'cramps', 'sorebreasts', 'fatigue',
       'sleepissue', 'moodswing', 'stress', 'foodcravings', 'indigestion',
       'bloating'],
      dtype='object')

,id,day_in_study,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,...,headaches,cramps,sorebreasts,fatigue,sleepissue,moodswing,stress,foodcravings,indigestion,bloating
0,1,1,753.0,64,5.498958,74.785346,1027.0,26.0,98.0,NaN,...,High,Very Low/Little,Very Low/Little,High,Low,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
1,1,2,855.0,74,5.372222,80.407307,77.0,4.0,95.0,NaN,...,Very High,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Moderate,Very Low/Little,Very Low/Little,Very Low/Little
2,1,3,751.0,159,5.579514,84.686869,502.0,28.0,95.0,NaN,...,High,Very Low/Little,Very Low/Little,Very High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
3,1,4,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,...,Very Low/Little,Very Low/Little,Very Low/Little,High,Very High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little
4,1,5,1430.0,10,5.381597,0.000000,NaN,NaN,NaN,NaN,...,Very Low/Little,Very Low/Little,Very Low/Little,High,High,Very Low/Little,Low,Very Low/Little,Very Low/Little,Very Low/Little

In [22]:
# Filter columns to features & target for Bayesian model
cols_to_keep = ['sedentary_mins', 'active_mins', 'glucose_mean', 'rhr_mean', 'minutes_asleep', 'minutes_awake',
'sleep_efficiency_mean', 'sleep_score_overall', 'sleep_score_revitalization', 'sleep_score_duration', 'lh', 'estrogen', 'phase']
features_target = data[cols_to_keep]
features_target.head()

,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,sleep_score_revitalization,sleep_score_duration,lh,estrogen,phase
0,753.0,64,5.498958,74.785346,1027.0,26.0,98.0,NaN,NaN,NaN,2.9,94.2,Follicular
1,855.0,74,5.372222,80.407307,77.0,4.0,95.0,NaN,NaN,NaN,1.2,226.3,Follicular
2,751.0,159,5.579514,84.686869,502.0,28.0,95.0,NaN,NaN,NaN,3.5,276.8,Follicular
3,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,22.0,37.0,1.8,322.1,Fertility
4,1430.0,10,5.381597,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.6,244.9,Fertility

In [23]:
# Check nan values
features_target.isna().sum()

sedentary_mins                  0
active_mins                     0
glucose_mean                  590
rhr_mean                        0
minutes_asleep                526
minutes_awake                 526
sleep_efficiency_mean         526
sleep_score_overall           450
sleep_score_revitalization    450
sleep_score_duration          450
lh                            223
estrogen                      224
phase                           1
dtype: int64

In [24]:
# Drop all nan values
features_target = features_target.dropna()
features_target.isna().sum()
features_target.head()

,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,sleep_score_revitalization,sleep_score_duration,lh,estrogen,phase
3,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,22.0,37.0,1.8,322.1,Fertility
6,805.0,117,5.343403,79.335861,467.0,51.0,97.0,81.0,21.0,42.0,5.0,364.7,Fertility
10,894.0,143,5.086111,76.317885,370.0,33.0,97.0,83.0,23.0,39.0,1.0,82.6,Luteal
11,914.0,86,5.035069,76.622706,398.0,42.0,96.0,80.0,22.0,39.0,2.7,137.6,Luteal
34,1073.0,22,5.238889,78.130659,311.0,34.0,94.0,81.0,24.0,36.0,17.7,208.0,Fertility

In [25]:
features_target.to_csv('cleaned_data.csv')

In [26]:
# Separate features and target
features = features_target.drop(columns = 'phase')
target = features_target['phase']
features.head()

,sedentary_mins,active_mins,glucose_mean,rhr_mean,minutes_asleep,minutes_awake,sleep_efficiency_mean,sleep_score_overall,sleep_score_revitalization,sleep_score_duration,lh,estrogen
3,905.0,86,5.206597,83.852219,384.0,65.0,93.0,80.0,22.0,37.0,1.8,322.1
6,805.0,117,5.343403,79.335861,467.0,51.0,97.0,81.0,21.0,42.0,5.0,364.7
10,894.0,143,5.086111,76.317885,370.0,33.0,97.0,83.0,23.0,39.0,1.0,82.6
11,914.0,86,5.035069,76.622706,398.0,42.0,96.0,80.0,22.0,39.0,2.7,137.6
34,1073.0,22,5.238889,78.130659,311.0,34.0,94.0,81.0,24.0,36.0,17.7,208.0

In [27]:
# Scale features 
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)
features_scaled

array([[ 0.45895124, -0.92692147, -0.241197  , ..., -0.07907009,
        -0.49705629,  1.55455189],
       [ 0.04484301, -0.67002961, -0.23474157, ...,  0.70069122,
        -0.05215262,  1.92204872],
       [ 0.41339933, -0.45457192, -0.24688236, ...,  0.23283443,
        -0.6082822 , -0.51153945],
       ...,
       [-0.74196262,  0.86303471, -0.17253022, ...,  0.70069122,
        -0.23289473, -0.48997273],
       [ 0.0241376 , -0.13967223, -0.1494283 , ..., -1.17073592,
        -0.42754009, -1.05502068],
       [-0.14150569,  0.57299551, -0.15096843, ..., -0.23502235,
        -0.37192713, -1.03345396]])